/**
 * ICAO NOTAM Q-code tables (Doc 8126 / Annex 15 NOTAM selection criteria):
 * the second and third letters of the Q code name the subject, the fourth
 * and fifth the condition. Generated on 2026-09-12 from two independent
 * drafts, reconciled and adversarially verified against the NAV CANADA
 * corpus (181 subjects, 80 conditions). A code not in
 * the tables decodes to null — never guessed. Regenerate with
 * scratchpad/gen-qcodes.cjs from a re-run of the icao-qcode-tables workflow.
 */

export interface QCodeEntry {
  readonly meaning: string;
  readonly group: string;
}

export const Q_SUBJECTS: Readonly<Record<string, QCodeEntry>> = {
  AA: { meaning: 'Minimum altitude (specify en-route/crossing/safe)', group: 'A' },
  AC: { meaning: 'Class B, C, D or E surface area (control zone)', group: 'A' },
  AD: { meaning: 'Air defence identification zone (ADIZ)', group: 'A' },
  AE: { meaning: 'Control area', group: 'A' },
  AF: { meaning: 'Flight information region', group: 'A' },
  AH: { meaning: 'Upper control area', group: 'A' },
  AL: { meaning: 'Minimum usable flight level', group: 'A' },
  AN: { meaning: 'Area navigation route', group: 'A' },
  AO: { meaning: 'Oceanic control area', group: 'A' },
  AP: { meaning: 'Reporting point (specify name)', group: 'A' },
  AR: { meaning: 'ATS route (specify)', group: 'A' },
  AT: { meaning: 'Class B, C, D or E terminal control area', group: 'A' },
  AU: { meaning: 'Upper flight information region', group: 'A' },
  AV: { meaning: 'Upper advisory area', group: 'A' },
  AX: { meaning: 'Significant point (intersection)', group: 'A' },
  AZ: { meaning: 'Aerodrome traffic zone', group: 'A' },
  CA: { meaning: 'Air/ground facility', group: 'C' },
  CB: { meaning: 'Automatic dependent surveillance - broadcast (ADS-B)', group: 'C' },
  CC: { meaning: 'Automatic dependent surveillance - contract (ADS-C)', group: 'C' },
  CD: { meaning: 'Controller-pilot data link communications (CPDLC)', group: 'C' },
  CE: { meaning: 'En-route surveillance radar', group: 'C' },
  CG: { meaning: 'Ground controlled approach system (GCA)', group: 'C' },
  CL: { meaning: 'Selective calling system (SELCAL)', group: 'C' },
  CM: { meaning: 'Surface movement radar', group: 'C' },
  CP: { meaning: 'Precision approach radar (PAR)', group: 'C' },
  CR: { meaning: 'Surveillance radar element of precision approach radar system', group: 'C' },
  CS: { meaning: 'Secondary surveillance radar (SSR)', group: 'C' },
  CT: { meaning: 'Terminal area surveillance radar (TAR)', group: 'C' },
  FA: { meaning: 'Aerodrome', group: 'F' },
  FB: { meaning: 'Friction measuring device', group: 'F' },
  FC: { meaning: 'Ceiling measurement equipment', group: 'F' },
  FD: { meaning: 'Docking system', group: 'F' },
  FE: { meaning: 'Oxygen', group: 'F' },
  FF: { meaning: 'Fire fighting and rescue', group: 'F' },
  FG: { meaning: 'Ground movement control', group: 'F' },
  FH: { meaning: 'Helicopter alighting area/platform', group: 'F' },
  FI: { meaning: 'Aircraft de-icing', group: 'F' },
  FJ: { meaning: 'Oils', group: 'F' },
  FL: { meaning: 'Landing direction indicator', group: 'F' },
  FM: { meaning: 'Meteorological service', group: 'F' },
  FO: { meaning: 'Fog dispersal system', group: 'F' },
  FP: { meaning: 'Heliport', group: 'F' },
  FS: { meaning: 'Snow removal equipment', group: 'F' },
  FT: { meaning: 'Transmissometer', group: 'F' },
  FU: { meaning: 'Fuel availability', group: 'F' },
  FW: { meaning: 'Wind direction indicator', group: 'F' },
  FZ: { meaning: 'Customs/immigration', group: 'F' },
  GA: { meaning: 'GNSS airfield-specific operations', group: 'G' },
  GW: { meaning: 'GNSS area-wide operations', group: 'G' },
  IC: { meaning: 'Instrument landing system (ILS)', group: 'I' },
  ID: { meaning: 'DME associated with ILS', group: 'I' },
  IG: { meaning: 'Glide path (ILS)', group: 'I' },
  II: { meaning: 'Inner marker (ILS)', group: 'I' },
  IL: { meaning: 'Localizer (ILS)', group: 'I' },
  IM: { meaning: 'Middle marker (ILS)', group: 'I' },
  IN: { meaning: 'Localizer (not associated with ILS)', group: 'I' },
  IO: { meaning: 'Outer marker (ILS)', group: 'I' },
  IS: { meaning: 'ILS Category I', group: 'I' },
  IT: { meaning: 'ILS Category II', group: 'I' },
  IU: { meaning: 'ILS Category III', group: 'I' },
  IW: { meaning: 'Microwave landing system (MLS)', group: 'I' },
  IX: { meaning: 'Locator, outer (ILS)', group: 'I' },
  IY: { meaning: 'Locator, middle (ILS)', group: 'I' },
  KK: { meaning: 'Checklist', group: 'K' },
  LA: { meaning: 'Approach lighting system', group: 'L' },
  LB: { meaning: 'Aerodrome beacon', group: 'L' },
  LC: { meaning: 'Runway centre line lights', group: 'L' },
  LD: { meaning: 'Landing direction indicator lights', group: 'L' },
  LE: { meaning: 'Runway edge lights', group: 'L' },
  LF: { meaning: 'Sequenced flashing lights', group: 'L' },
  LG: { meaning: 'Pilot-controlled lighting', group: 'L' },
  LH: { meaning: 'High intensity runway lights', group: 'L' },
  LI: { meaning: 'Runway end identifier lights', group: 'L' },
  LJ: { meaning: 'Runway alignment indicator lights', group: 'L' },
  LK: { meaning: 'Category II components of approach lighting system', group: 'L' },
  LL: { meaning: 'Low intensity runway lights', group: 'L' },
  LM: { meaning: 'Medium intensity runway lights', group: 'L' },
  LP: { meaning: 'Precision approach path indicator (PAPI)', group: 'L' },
  LR: { meaning: 'All landing area lighting facilities', group: 'L' },
  LS: { meaning: 'Stopway lights', group: 'L' },
  LT: { meaning: 'Threshold lights', group: 'L' },
  LU: { meaning: 'Helicopter approach path indicator', group: 'L' },
  LV: { meaning: 'Visual approach slope indicator system', group: 'L' },
  LW: { meaning: 'Heliport lighting', group: 'L' },
  LX: { meaning: 'Taxiway centre line lights', group: 'L' },
  LY: { meaning: 'Taxiway edge lights', group: 'L' },
  LZ: { meaning: 'Runway touchdown zone lights', group: 'L' },
  MA: { meaning: 'Movement area', group: 'M' },
  MB: { meaning: 'Bearing strength', group: 'M' },
  MC: { meaning: 'Clearway', group: 'M' },
  MD: { meaning: 'Declared distances', group: 'M' },
  MG: { meaning: 'Taxiing guidance system', group: 'M' },
  MH: { meaning: 'Runway arresting gear', group: 'M' },
  MK: { meaning: 'Parking area', group: 'M' },
  MM: { meaning: 'Daylight markings', group: 'M' },
  MN: { meaning: 'Apron', group: 'M' },
  MO: { meaning: 'Stopbar', group: 'M' },
  MP: { meaning: 'Aircraft stands', group: 'M' },
  MR: { meaning: 'Runway', group: 'M' },
  MS: { meaning: 'Stopway', group: 'M' },
  MT: { meaning: 'Threshold', group: 'M' },
  MU: { meaning: 'Runway turning bay', group: 'M' },
  MW: { meaning: 'Strip/shoulder', group: 'M' },
  MX: { meaning: 'Taxiway(s)', group: 'M' },
  MY: { meaning: 'Rapid exit taxiway(s)', group: 'M' },
  NA: { meaning: 'All radio navigation facilities (except those listed separately)', group: 'N' },
  NB: { meaning: 'Nondirectional radio beacon (NDB)', group: 'N' },
  NC: { meaning: 'DECCA', group: 'N' },
  ND: { meaning: 'Distance measuring equipment (DME)', group: 'N' },
  NF: { meaning: 'Fan marker', group: 'N' },
  NL: { meaning: 'Locator (specify identification)', group: 'N' },
  NM: { meaning: 'VOR/DME', group: 'N' },
  NN: { meaning: 'TACAN', group: 'N' },
  NO: { meaning: 'OMEGA', group: 'N' },
  NT: { meaning: 'VORTAC', group: 'N' },
  NV: { meaning: 'VOR', group: 'N' },
  NX: { meaning: 'Direction-finding station (specify type)', group: 'N' },
  OA: { meaning: 'Aeronautical information service', group: 'O' },
  OB: { meaning: 'Obstacle', group: 'O' },
  OE: { meaning: 'Aircraft entry requirements', group: 'O' },
  OL: { meaning: 'Obstacle lights on (specify)', group: 'O' },
  OR: { meaning: 'Rescue coordination centre', group: 'O' },
  PA: { meaning: 'Standard instrument arrival (STAR)', group: 'P' },
  PB: { meaning: 'Standard VFR arrival', group: 'P' },
  PC: { meaning: 'Contingency procedures', group: 'P' },
  PD: { meaning: 'Standard instrument departure (SID)', group: 'P' },
  PE: { meaning: 'Standard VFR departure', group: 'P' },
  PF: { meaning: 'Flow control procedure', group: 'P' },
  PH: { meaning: 'Holding procedure', group: 'P' },
  PI: { meaning: 'Instrument approach procedure', group: 'P' },
  PK: { meaning: 'VFR approach procedure', group: 'P' },
  PL: { meaning: 'Flight plan processing', group: 'P' },
  PM: { meaning: 'Aerodrome operating minima', group: 'P' },
  PN: { meaning: 'Noise operating restriction', group: 'P' },
  PO: { meaning: 'Obstacle clearance altitude and height', group: 'P' },
  PR: { meaning: 'Radio failure procedure', group: 'P' },
  PT: { meaning: 'Transition altitude or transition level', group: 'P' },
  PU: { meaning: 'Missed approach procedure', group: 'P' },
  PX: { meaning: 'Minimum holding altitude', group: 'P' },
  PZ: { meaning: 'ADIZ procedure', group: 'P' },
  RA: { meaning: 'Airspace reservation', group: 'R' },
  RD: { meaning: 'Danger area', group: 'R' },
  RM: { meaning: 'Military operating area', group: 'R' },
  RO: { meaning: 'Overflying of (specify)', group: 'R' },
  RP: { meaning: 'Prohibited area', group: 'R' },
  RR: { meaning: 'Restricted area', group: 'R' },
  RT: { meaning: 'Temporary restricted area', group: 'R' },
  SA: { meaning: 'Automatic terminal information service (ATIS)', group: 'S' },
  SB: { meaning: 'ATS reporting office', group: 'S' },
  SC: { meaning: 'Area control centre', group: 'S' },
  SE: { meaning: 'Flight information service', group: 'S' },
  SF: { meaning: 'Aerodrome flight information service', group: 'S' },
  SL: { meaning: 'Flow control centre', group: 'S' },
  SO: { meaning: 'Oceanic area control centre', group: 'S' },
  SP: { meaning: 'Approach control service', group: 'S' },
  SS: { meaning: 'Flight service station', group: 'S' },
  ST: { meaning: 'Aerodrome control tower', group: 'S' },
  SU: { meaning: 'Upper area control centre', group: 'S' },
  SV: { meaning: 'VOLMET broadcast', group: 'S' },
  SY: { meaning: 'Upper advisory service', group: 'S' },
  WA: { meaning: 'Air display', group: 'W' },
  WB: { meaning: 'Aerobatics', group: 'W' },
  WC: { meaning: 'Captive balloon or kite', group: 'W' },
  WD: { meaning: 'Demolition of explosives', group: 'W' },
  WE: { meaning: 'Exercises', group: 'W' },
  WF: { meaning: 'Air refuelling', group: 'W' },
  WG: { meaning: 'Glider flying', group: 'W' },
  WH: { meaning: 'Blasting', group: 'W' },
  WJ: { meaning: 'Banner/target towing', group: 'W' },
  WL: { meaning: 'Ascent of free balloon', group: 'W' },
  WM: { meaning: 'Missile, gun or rocket firing', group: 'W' },
  WP: { meaning: 'Parachute jumping exercise, paragliding or hang gliding', group: 'W' },
  WR: { meaning: 'Radioactive materials or toxic chemicals', group: 'W' },
  WS: { meaning: 'Burning or blowing gas', group: 'W' },
  WT: { meaning: 'Mass movement of aircraft', group: 'W' },
  WU: { meaning: 'Unmanned aircraft', group: 'W' },
  WV: { meaning: 'Formation flight', group: 'W' },
  WW: { meaning: 'Significant volcanic activity', group: 'W' },
  WY: { meaning: 'Aerial survey', group: 'W' },
  WZ: { meaning: 'Model flying', group: 'W' },
  XX: { meaning: 'Other (specify in plain language)', group: 'X' },
};

export const Q_CONDITIONS: Readonly<Record<string, QCodeEntry>> = {
  AC: { meaning: 'Withdrawn for maintenance', group: 'A' },
  AD: { meaning: 'Available for daylight operation', group: 'A' },
  AF: { meaning: 'Flight checked and found reliable', group: 'A' },
  AG: { meaning: 'Operating but ground checked only, awaiting flight check', group: 'A' },
  AH: { meaning: 'Hours of service are now (specify)', group: 'A' },
  AK: { meaning: 'Resumed normal operations', group: 'A' },
  AL: { meaning: 'Operative (or reoperative) subject to previously published limitations/conditions', group: 'A' },
  AM: { meaning: 'Military operations only', group: 'A' },
  AN: { meaning: 'Available for night operation', group: 'A' },
  AO: { meaning: 'Operational', group: 'A' },
  AP: { meaning: 'Available, prior permission required', group: 'A' },
  AR: { meaning: 'Available on request', group: 'A' },
  AS: { meaning: 'Unserviceable', group: 'A' },
  AU: { meaning: 'Not available', group: 'A' },
  AW: { meaning: 'Completely withdrawn', group: 'A' },
  AX: { meaning: 'Previously promulgated shutdown has been cancelled', group: 'A' },
  CA: { meaning: 'Activated', group: 'C' },
  CC: { meaning: 'Completed', group: 'C' },
  CD: { meaning: 'Deactivated', group: 'C' },
  CE: { meaning: 'Erected', group: 'C' },
  CF: { meaning: 'Operating frequency(ies) changed to', group: 'C' },
  CG: { meaning: 'Downgraded to', group: 'C' },
  CH: { meaning: 'Changed', group: 'C' },
  CI: { meaning: 'Identification or radio call sign changed to', group: 'C' },
  CL: { meaning: 'Realigned', group: 'C' },
  CM: { meaning: 'Displaced', group: 'C' },
  CN: { meaning: 'Cancelled', group: 'C' },
  CO: { meaning: 'Operating', group: 'C' },
  CP: { meaning: 'Operating on reduced power', group: 'C' },
  CR: { meaning: 'Temporarily replaced by', group: 'C' },
  CS: { meaning: 'Installed', group: 'C' },
  CT: { meaning: 'On test, do not use', group: 'C' },
  HA: { meaning: 'Braking action is (specify)', group: 'H' },
  HB: { meaning: 'Friction coefficient is (specify)', group: 'H' },
  HC: { meaning: 'Covered by compacted snow to a depth of', group: 'H' },
  HD: { meaning: 'Covered by dry snow to a depth of', group: 'H' },
  HE: { meaning: 'Covered by water to a depth of', group: 'H' },
  HF: { meaning: 'Totally free of snow and ice', group: 'H' },
  HG: { meaning: 'Grass cutting in progress', group: 'H' },
  HH: { meaning: 'Hazard due to (specify)', group: 'H' },
  HI: { meaning: 'Covered by ice', group: 'H' },
  HJ: { meaning: 'Launch planned (specify balloon flight identification or project code name)', group: 'H' },
  HK: { meaning: 'Bird migration in progress', group: 'H' },
  HL: { meaning: 'Snow clearance completed', group: 'H' },
  HM: { meaning: 'Marked by', group: 'H' },
  HN: { meaning: 'Covered by wet snow or slush to a depth of', group: 'H' },
  HO: { meaning: 'Obscured by snow', group: 'H' },
  HP: { meaning: 'Snow clearance in progress', group: 'H' },
  HQ: { meaning: 'Operation cancelled (specify balloon flight identification or project code name)', group: 'H' },
  HR: { meaning: 'Standing water', group: 'H' },
  HS: { meaning: 'Sanding in progress', group: 'H' },
  HT: { meaning: 'Approach according to signal area only', group: 'H' },
  HU: { meaning: 'Launch in progress (specify balloon flight identification or project code name)', group: 'H' },
  HV: { meaning: 'Work completed', group: 'H' },
  HW: { meaning: 'Work in progress', group: 'H' },
  HX: { meaning: 'Concentration of birds', group: 'H' },
  HY: { meaning: 'Snow banks exist (specify height)', group: 'H' },
  HZ: { meaning: 'Covered by frozen ruts and ridges', group: 'H' },
  KK: { meaning: 'Checklist', group: 'K' },
  LA: { meaning: 'Operating on auxiliary power supply', group: 'L' },
  LB: { meaning: 'Reserved for aircraft based therein', group: 'L' },
  LC: { meaning: 'Closed', group: 'L' },
  LD: { meaning: 'Unsafe', group: 'L' },
  LE: { meaning: 'Operating without auxiliary power supply', group: 'L' },
  LF: { meaning: 'Interference from', group: 'L' },
  LG: { meaning: 'Operating without identification', group: 'L' },
  LH: { meaning: 'Unserviceable for aircraft heavier than', group: 'L' },
  LI: { meaning: 'Closed to IFR operations', group: 'L' },
  LK: { meaning: 'Operating as a fixed light', group: 'L' },
  LL: { meaning: 'Usable for length of ... and width of ...', group: 'L' },
  LN: { meaning: 'Closed to all night operations', group: 'L' },
  LP: { meaning: 'Prohibited to', group: 'L' },
  LR: { meaning: 'Aircraft restricted to runways and taxiways', group: 'L' },
  LS: { meaning: 'Subject to interruption', group: 'L' },
  LT: { meaning: 'Limited to', group: 'L' },
  LV: { meaning: 'Closed to VFR operations', group: 'L' },
  LW: { meaning: 'Will take place', group: 'L' },
  LX: { meaning: 'Operating but caution advised due to', group: 'L' },
  TT: { meaning: 'Trigger NOTAM', group: 'X' },
  XX: { meaning: 'Other (specify in plain language)', group: 'X' },
};

export const Q_TRAFFIC: Readonly<Record<string, string>> = {
  I: 'IFR',
  IV: 'IFR and VFR',
  K: 'NOTAM is a checklist',
  V: 'VFR',
};

export const Q_PURPOSE: Readonly<Record<string, string>> = {
  B: 'NOTAM of operational significance selected for PIB entry',
  BO: 'PIB entry and concerning flight operations',
  K: 'NOTAM is a checklist',
  M: 'Miscellaneous NOTAM; not subject for briefing, but available on request',
  N: 'NOTAM selected for the immediate attention of aircraft operators',
  NBO: 'Immediate attention of aircraft operators, PIB entry, and concerning flight operations',
  O: 'NOTAM concerning flight operations',
};

export const Q_SCOPE: Readonly<Record<string, string>> = {
  A: 'Aerodrome',
  AE: 'Aerodrome and en-route',
  AW: 'Aerodrome and navigation warning',
  E: 'En-route',
  K: 'NOTAM is a checklist',
  W: 'Navigation warning',
};

export interface QCodeMeaning {
  readonly subject: string | null;
  readonly condition: string | null;
  readonly traffic: string | null;
  readonly purpose: string | null;
  readonly scope: string | null;
}

/** Look up a combined indicator (`NBO`) directly, else letter by letter. */
function indicator(table: Readonly<Record<string, string>>, letters: string): string | null {
  if (table[letters]) return table[letters]!;
  const parts = [...letters].map((c) => table[c] ?? null);
  return parts.length > 0 && parts.every((p) => p !== null) ? parts.join(', ') : null;
}

/** Decode a Q line's codes to words. Any part not in the tables is null. */
export function describeQCode(q: {
  readonly code: { readonly subject: string; readonly condition: string };
  readonly traffic: string;
  readonly purpose: string;
  readonly scope: string;
}): QCodeMeaning {
  return {
    subject: Q_SUBJECTS[q.code.subject]?.meaning ?? null,
    condition: Q_CONDITIONS[q.code.condition]?.meaning ?? null,
    traffic: indicator(Q_TRAFFIC, q.traffic),
    purpose: indicator(Q_PURPOSE, q.purpose),
    scope: indicator(Q_SCOPE, q.scope),
  };
}
